// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39IKQpSZbW-X6aW84fy_7Q4fjf4qyCuk',
    appId: '1:863641382611:web:9ec1b3ae90f32fd0886e26',
    messagingSenderId: '863641382611',
    projectId: 'cooker-app-2024',
    authDomain: 'cooker-app-2024.firebaseapp.com',
    storageBucket: 'cooker-app-2024.appspot.com',
    measurementId: 'G-FEK03FHSS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hrjBToAtIE44J7Zl6joYoy6jGbugmL0',
    appId: '1:863641382611:android:2118232a2b476e2a886e26',
    messagingSenderId: '863641382611',
    projectId: 'cooker-app-2024',
    storageBucket: 'cooker-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OqYFWUZLrQ2RcW5j0xyfg_nU5k1HgQw',
    appId: '1:863641382611:ios:bc263b9a93fd7825886e26',
    messagingSenderId: '863641382611',
    projectId: 'cooker-app-2024',
    storageBucket: 'cooker-app-2024.appspot.com',
    iosBundleId: 'com.example.cookerApp',
  );
}
